package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    params {
        add {
            password("system.client_id", "credentialsJSON:6a559562-d646-49b6-beef-a8ba26f95623", label = "client_id", display = ParameterDisplay.HIDDEN)
        }
    }
}
