version: "3.9"

services:
  postgres:
    image: zackjohnson8/stockwatch-database:latest
    restart: always
    build:
      context: .
      dockerfile: ./docker/database/dockerfile/postgres_database.Dockerfile
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=stockdata
      - POSTGRES_DB=stockdata
    volumes:
      - ./docker/database_volumes/database/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    image: zackjohnson8/stockwatch-adminer:latest
    restart: always
    build:
      context: .
      dockerfile: ./docker/database/dockerfile/adminer_database_gui.Dockerfile
    ports:
      - '8080:8080'